# Generated by Django 4.2.30 on 2026-05-28 19:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RewriteHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_text', models.TextField()),
                ('output_text', models.TextField()),
                ('mode', models.CharField(max_length=20)),
                ('tone', models.CharField(blank=True, max_length=30, null=True)),
                ('length', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rewrites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Rewrite Histories',
                'ordering': ['-created_at'],
            },
        ),
    ]
